### ISSUE TITLE
No LICENSE?

### ISSUE THREAD

**Issue by bangert** [el-davo/ng-oauth2#1]
Hi,

ng-oauth2 is looking good. Thanks for sharing!
Could you clarify the license this project is under?
Thanks

**Comment by el-davo** [comment]
Hi I will add MIT license when i get the chance. Feel free to use.

**Comment by bangert** [comment]
awesome - thank you!

**Comment by el-davo** [comment]
Thanks for reporting. Have updated bower.json, package.json and the Readme and cut a release to 0.0.6

Closing this issue now
